/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudioRouteRouteImport } from './routes/studio/route'
import { Route as StudioIndexRouteImport } from './routes/studio/index'
import { Route as StudioAgentRouteImport } from './routes/studio/agent'
import { Route as StudioLibraryRouteImport } from './routes/studio/library'
import { Route as StudioPIdRouteImport } from './routes/studio/p.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRouteRoute = StudioRouteRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudioRouteRoute,
} as any)
const StudioAgentRoute = StudioAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => StudioRouteRoute,
} as any)
const StudioLibraryRoute = StudioLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => StudioRouteRoute,
} as any)
const StudioPIdRoute = StudioPIdRouteImport.update({
  id: '/p/$id',
  path: '/p/$id',
  getParentRoute: () => StudioRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/studio': typeof StudioRouteRouteWithChildren
  '/studio/agent': typeof StudioAgentRoute
  '/studio/library': typeof StudioLibraryRoute
  '/studio/': typeof StudioIndexRoute
  '/studio/p/$id': typeof StudioPIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/studio/agent': typeof StudioAgentRoute
  '/studio/library': typeof StudioLibraryRoute
  '/studio': typeof StudioIndexRoute
  '/studio/p/$id': typeof StudioPIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/studio': typeof StudioRouteRouteWithChildren
  '/studio/agent': typeof StudioAgentRoute
  '/studio/library': typeof StudioLibraryRoute
  '/studio/': typeof StudioIndexRoute
  '/studio/p/$id': typeof StudioPIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/studio'
    | '/studio/agent'
    | '/studio/library'
    | '/studio/'
    | '/studio/p/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/studio/agent' | '/studio/library' | '/studio' | '/studio/p/$id'
  id:
    | '__root__'
    | '/'
    | '/studio'
    | '/studio/agent'
    | '/studio/library'
    | '/studio/'
    | '/studio/p/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StudioRouteRoute: typeof StudioRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/': {
      id: '/studio/'
      path: '/'
      fullPath: '/studio/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof StudioRouteRoute
    }
    '/studio/agent': {
      id: '/studio/agent'
      path: '/agent'
      fullPath: '/studio/agent'
      preLoaderRoute: typeof StudioAgentRouteImport
      parentRoute: typeof StudioRouteRoute
    }
    '/studio/library': {
      id: '/studio/library'
      path: '/library'
      fullPath: '/studio/library'
      preLoaderRoute: typeof StudioLibraryRouteImport
      parentRoute: typeof StudioRouteRoute
    }
    '/studio/p/$id': {
      id: '/studio/p/$id'
      path: '/p/$id'
      fullPath: '/studio/p/$id'
      preLoaderRoute: typeof StudioPIdRouteImport
      parentRoute: typeof StudioRouteRoute
    }
  }
}

interface StudioRouteRouteChildren {
  StudioAgentRoute: typeof StudioAgentRoute
  StudioLibraryRoute: typeof StudioLibraryRoute
  StudioIndexRoute: typeof StudioIndexRoute
  StudioPIdRoute: typeof StudioPIdRoute
}

const StudioRouteRouteChildren: StudioRouteRouteChildren = {
  StudioAgentRoute: StudioAgentRoute,
  StudioLibraryRoute: StudioLibraryRoute,
  StudioIndexRoute: StudioIndexRoute,
  StudioPIdRoute: StudioPIdRoute,
}

const StudioRouteRouteWithChildren = StudioRouteRoute._addFileChildren(
  StudioRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StudioRouteRoute: StudioRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
