import { mkdir, readFile, rm, stat, writeFile } from "node:fs/promises";
import path from "node:path";
import type { Response } from "express";
import type { Config } from "./config";

export type SendOptions = { contentType: string; downloadName?: string };

/** Where voice takes, product photos and finished videos live. Keys are generated by the server only. */
export interface Storage {
  put(key: string, body: Buffer, contentType: string): Promise<void>;
  read(key: string): Promise<Buffer | null>;
  remove(key: string): Promise<void>;
  /** Streams (or redirects to) the object; supports HTTP range requests for video seeking. */
  send(res: Response, key: string, options: SendOptions): Promise<void>;
}

const SAFE_KEY = /^[A-Za-z0-9][A-Za-z0-9/_.-]*$/;

export function assertKey(key: string) {
  if (!SAFE_KEY.test(key) || key.includes("..") || key.includes("//")) {
    throw new Error(`Unsafe storage key: ${key}`);
  }
}

function disposition(name: string) {
  const ascii = name.replace(/[^A-Za-z0-9._-]+/g, "-").slice(0, 80) || "castly";
  return `attachment; filename="${ascii}"`;
}

export class LocalStorage implements Storage {
  private readonly root: string;

  constructor(dir: string) {
    this.root = path.resolve(dir);
  }

  private file(key: string) {
    assertKey(key);
    return path.join(this.root, key);
  }

  async put(key: string, body: Buffer) {
    const file = this.file(key);
    await mkdir(path.dirname(file), { recursive: true });
    await writeFile(file, body);
  }

  async read(key: string) {
    try {
      return await readFile(this.file(key));
    } catch {
      return null;
    }
  }

  async remove(key: string) {
    await rm(this.file(key), { force: true });
  }

  async send(res: Response, key: string, options: SendOptions) {
    const file = this.file(key);
    try {
      await stat(file);
    } catch {
      res.status(404).json({ error: { code: "not_found", message: "That file is gone." } });
      return;
    }
    const headers: Record<string, string> = {
      "Content-Type": options.contentType,
      "Cache-Control": "private, max-age=3600",
    };
    if (options.downloadName) headers["Content-Disposition"] = disposition(options.downloadName);
    await new Promise<void>((resolve, reject) => {
      res.sendFile(file, { headers, dotfiles: "deny" }, (err) => (err && !res.headersSent ? reject(err) : resolve()));
    });
  }
}

type S3Settings = Extract<Config["storage"], { driver: "s3" }>;

export class S3Storage implements Storage {
  private clientPromise: Promise<import("@aws-sdk/client-s3").S3Client> | null = null;

  constructor(private readonly settings: S3Settings) {}

  private async client() {
    this.clientPromise ??= import("@aws-sdk/client-s3").then(
      ({ S3Client }) =>
        new S3Client({
          region: this.settings.region,
          endpoint: this.settings.endpoint,
          forcePathStyle: Boolean(this.settings.endpoint),
          credentials:
            this.settings.accessKeyId && this.settings.secretAccessKey
              ? { accessKeyId: this.settings.accessKeyId, secretAccessKey: this.settings.secretAccessKey }
              : undefined,
        }),
    );
    return this.clientPromise;
  }

  async put(key: string, body: Buffer, contentType: string) {
    assertKey(key);
    const { PutObjectCommand } = await import("@aws-sdk/client-s3");
    await (await this.client()).send(
      new PutObjectCommand({ Bucket: this.settings.bucket, Key: key, Body: body, ContentType: contentType }),
    );
  }

  async read(key: string) {
    assertKey(key);
    const { GetObjectCommand } = await import("@aws-sdk/client-s3");
    try {
      const out = await (await this.client()).send(new GetObjectCommand({ Bucket: this.settings.bucket, Key: key }));
      const bytes = await out.Body?.transformToByteArray();
      return bytes ? Buffer.from(bytes) : null;
    } catch {
      return null;
    }
  }

  async remove(key: string) {
    assertKey(key);
    const { DeleteObjectCommand } = await import("@aws-sdk/client-s3");
    await (await this.client()).send(new DeleteObjectCommand({ Bucket: this.settings.bucket, Key: key }));
  }

  async send(res: Response, key: string, options: SendOptions) {
    assertKey(key);
    const [{ GetObjectCommand }, { getSignedUrl }] = await Promise.all([
      import("@aws-sdk/client-s3"),
      import("@aws-sdk/s3-request-presigner"),
    ]);
    const url = await getSignedUrl(
      await this.client(),
      new GetObjectCommand({
        Bucket: this.settings.bucket,
        Key: key,
        ResponseContentType: options.contentType,
        ResponseContentDisposition: options.downloadName ? disposition(options.downloadName) : undefined,
      }),
      { expiresIn: 600 },
    );
    res.redirect(302, url);
  }
}

export function createStorage(config: Config): Storage {
  return config.storage.driver === "s3" ? new S3Storage(config.storage) : new LocalStorage(config.storage.dir);
}
